---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  labels:
    app: master-service
spec:
  ports:
    - port: 80
      name: master
  clusterIP: None
  selector:
    app: master-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
    app: master-service
spec:
  serviceName: "master-service"
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: master-service
  replicas: 1
  template:
    metadata:
      labels:
        app: master-service
    spec:
      containers:
        - name: master-service
          image: liabifano/hogwild:latest
          env:
            - name: N_THREADS
              valueFrom:
                configMapKeyRef:
                  name: hw-config
                  key: threads
            - name: RUNNING_MODE
              valueFrom:
                configMapKeyRef:
                  name: hw-config
                  key: running_mode
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: hw-config
                  key: data_path
          resources:
            requests:
              memory: "20Gi"
              cpu: "4000m"
            limits:
              memory: "20Gi"
              cpu: "4000m"
          ports:
            - containerPort: 80
              name: master
          command: ["python", "mil-2/master.py"]
          volumeMounts:
            - name: shared-volume
              mountPath: /data
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cs449g7-scratch
